Dockerfile.cpu, Dockerfile.gpu
An alternate strategy I considered was using non-unique-uid users (the `--non-unique` option of `useradd`) to add an alias user to `nobody` with the same UID as the `nobody` user, but then when launching docker containers, to specify the user by name instead of by UID.  This is apparently a behavior that exists in Linux but from what I can tell it is discouraged as being non-standard and kinda fragile.
We could also have just set the `nobody` user's `HOME` to a real directory, but IMO it is best to leave the `nobody` user in its default state.
Users wanting to have the same features in custom images will have to duplicate these lines from our Dockerfiles, which is why I left comments explaining the situations where they are useful.
=> [DET-3184] Add a det-nobody user.

cloud/environments-packer.json
Upgrading to a newer kernel version so we can mount FSx for Lustre
=> Upgraded base agent VM images to Ubuntu 18.04

cloud/environments-packer.json
Last commit using 18.04 had a build failure. Revert to 16.04 instead of debugging since there's no important reason to use 16.04 right now.
=> Revert base image to most recent release of 16.04 

Dockerfile.cpu, Dockerfile.gpu, libnss_determined/.clang-format, libnss_determined/.gitignore, libnss_determined/Dockerfile, libnss_determined/Makefile, libnss_determined/README.md, libnss_determined/src/group.c, libnss_determined/src/libnss_determined.h, libnss_determined/src/parse.c, libnss_determined/src/passwd.c, libnss_determined/src/shadow.c, libnss_determined/src/util.c, libnss_determined/test/integration_test.sh, libnss_determined/test/unit_test.c
libnss_determined is a plugin to glibc's name switch service.  It allows
us to provision users in the container at runtime, which allows for easy
support of features like sshd and distributed training in non-root
containers.
About half of the code is dedicated to implementing parsing functions.  I originally used the built-in `fgetpwent`, `fgetgrent`, and `fgetspent` for reading lines out of files formatted like `/etc/passwd`, `/etc/group`, and `/etc/shadow`, respectively, but those broke in our containers due to `LC_*` environment variables.  Probably we could do something to the locale in the container to fix the underlying issue, but I figure if we expect users to include this thing in their custom environments, we should just implement the parsing ourselves in a way that is robust to …
=> Introduce libnss_determined.

cloud/roles/nvidia-drivers/defaults/main.yml
Upgrade from 410.104 to 450.51.05. This apparently is necessary to get
T4 chips to work on G4 AWS instances. This driver *should* be compatible
with older versions of CUDA -- I tested with CUDA 10.0 only.
Along the way, switch from the "XFree86" package to the "Tesla" package.
It is a little unclear what the difference is, but the Nvidia download
site guides you to the latter when you're using enterprise GPUs, which
should always be the case in public cloud environments.
=> fix: Update version of Nvidia driver in cloud images.

cloud/roles/nvidia-drivers/tasks/main.yml
The path to the persistence daemon change when the Nvidia drivers were
upgraded in #45.
=> fix: Update to reflect change in NVIDIA GLX paths.

.circleci/config.yml, Makefile, scripts/publish-docker.sh
The artifacts will eventually be consumed by scripts in the main
Determined repository for automatically updating the image tags.
=> Save parsable artifacts after publishing.

Dockerfile.cpu, Dockerfile.gpu, cloud/environments-packer.json, cloud/roles/journald-cloudwatch/defaults/main.yml
I think we will have to manually verify that the journald-to-cloudwatch stuff still works afterwards.
=> Remove references to PEDL.

cloud/environments-packer.json
Note that `eu-west-2` (London) does not have p2.8xlarge instance types (our default image type for `det-deploy`) which means it will require special handling.  However, the London region was specifically requested by an OSS user, so I think it's worth supporting.
All other regions added here support P3 instances and also the p2.8xlarge instances that we use by default.
=> Add P3-instance regions.

Dockerfile.cpu, Dockerfile.gpu
Nvidia's security scan found several exposed private keys - we simply remove them.
=> chore: remove ssh private keys

Dockerfile.cpu, Dockerfile.gpu
The cache should never need to be used, and it adds around a gigabyte to
the size of each image (a bit more for GPU ones).
(Testing: I ran a CPU image build locally and checked that the cache doesn't appear and the image is smaller by the expected amount.)
=> chore: disable caching for all Pip installs

cloud/environments-packer.json
Already added keys to do this to the determined-production context in CircleCI.
Haven't tested Packer locally - may still do that if it proves to be easy enough.
Note: using west because it has p2 instances (east doesn't), but pushing to east just in case it's ever needed there - AFAIK that's a trivial cost. Tried to go with a nearly identical image: recent build of Ubuntu Xenial (16.04) with the same specs and similar naming convention as what we use on non-GovCloud.
=> chore: Publish images to AWS GovCloud [DET-4985]

.circleci/config.yml
If you don't install this, the workflow fails because it gets a non-zero status from "ansible-playbook --version". If you dig deeper, it's because some Python code in the CLI tries to import the Ansible Python module and it doesn't exist unless you've installed it. I've reported this on their IRC channel - seems to be the only point of contact I see on Launchpad.
I actually see this in Ubuntu 20.04 in general even when installing the stock / upstream Ansible deb package too. I'm still using the PPA we used to use because as of today, their Ubuntu 20.04 distribution is fixed with the new release.
=> chore: also install Ansible Python package

.circleci/config.yml
Turns out we have to `apt-get update` to get the Rust compiler anyway... I've since learning that upgrading Pip is the better long-term solution anyway. Tried this out via a SSH to try and stop this series of band-aids...
(side note: other failures in CircleCI yesterday were because the Hashicorp releases server was misconfigured)
=> chore: Upgrade pip to avoid need for Rust compiler

Dockerfile.cpu, Dockerfile.gpu, Makefile
with pytorch_lightning `determinedai/environments                       cuda-11.0-pytorch-1.7-tf-2.4-gpu-0.9.0      bd4b268027b4   2 hours ago     13.6GB`
without pytorch_lightning `determinedai/environments                       cuda-11.0-pytorch-1.7-tf-2.4-gpu-83fb707    bff7363d121c   5 minutes ago   13.5GB`
I tested by building the above image and using it to run a pytorch_lightning experiment
=> build: add pytorch_lightning to env images

Makefile, cloud/environments-packer.json, scripts/publish-docker.sh
* Use the complete DockerHub path when downloading for cloud images
* Only write to artifacts for the DockerHub downloads
=> chore: fix Docker publishing code

cloud/environments-packer.json
There are 2 Ansible playbook invocations, an AWS-specific one and a GCP-specific one. Right now neither runs for the GovCloud builder - so having the AWS one apply to both.
=> chore: Run Ansible playbook on both AWS builders

Makefile, cloud/environments-packer.json, cloud/roles/environments/tasks/main.yml
This step was missed previously. Also, removing a reference to the other CUDA 11 image that's not actually ready.
=> fix: pre-load CUDA 11 environment into cloud images

cloud/roles/gpumon/files/gpumon, cloud/roles/gpumon/tasks/main.yml, cloud/roles/nvidia-docker/tasks/main.yml
Confirmed the new repository URLs on NVIDIA's site, confirmed the new package name on my local Ubuntu 12.04 system, and confirmed the modified gpumon script at least parses correctly in Python 3.7.
=> chore: switch to Ubuntu 20.04 repositories and Python 3

Dockerfile.cpu, Makefile
This is a part of the upcoming CPU-only distributed training feature. It adds about 20M to the image size.
Also, remove redundant `HOROVOD_WITH_TENSORFLOW` and `HOROVOD_WITH_PYTORCH` arguments on the GPU images, as these are default values anyway.
Intended to be landed after https://github.com/determined-ai/environments/pull/94
=> feat: add horovod to CPU images.

Dockerfile-base-cpu, Dockerfile-base-gpu
Nvidia NGC wants our images to have no high severity vulnerabilities. We are currently exposed to https://ubuntu.com/security/CVE-2021-3449
Let's automatically run security upgrades only (via `unattended-upgrades`). These are supposed to be low-risk upgrades.
=> fix: always apply security upgrades to base images.

Makefile
We've hit the silent packer errors again today. 
I've realized we are doing `packer | tee` which is eating the errors by default. Using `bash -o pipefail` should fix that while not breaking anything else.
=> fix: make jobs fail on packer errors [DET-5876]

.circleci/config.yml, Makefile
Packer fails from time to time, and rerunning CircleCI job *does not work* because there're artifacts from the previous run. `-force` can override that. As usual, we've got to use it with care and not rerun published builds.
=> feat: run `packer build -force` in CI to allow reruns on failures.

.circleci/config.yml
Was missed in a hastily merged #126
=> ci: add ROCm image to circleci build.

.circleci/config.yml, Dockerfile-default-gpu, Makefile, dockerfile_scripts/additional-requirements.txt, dockerfile_scripts/install_deepspeed.sh
Adding a deepspeed docker image for our deepspeed support.  I originally wanted to build it into our default tf2 gpu image but deepspeed is not compatible with 3.7 cuda arch.  As part of deepspeed installation, custom ops are prebuilt to reduce overhead for JIT during training.
=> feat: add deepspeed docker env

Makefile
Fix make method to publish gpt-neox deepspeed image.
=> fix gpt-neox deepspeed publish method

Makefile
Bump version for deepspeed image to 0.6.0.  Note that this does not affect the gpt-neox image which is tied to a specific branch of deepspeed.
=> update to deepspeed 0.6.0

Makefile, scripts/publish-docker.sh
bumpenvs relies on artifacts being published for all environment images. The previous change that enabled building multi-platform images for tf2 and tf27 relied on docker buildx to push images to the repository but I forgot to make sure that the corresponding artifacts be published on circleci.
=> fix: publish artifacts for multiplatform images

Makefile
We need to differentiate between artifacts built with or without mpi as part of bumpenvs in the main repo.  This PR adds a MPI flag to the artifact path for each job.
=> add mpi suffix to artifact log names

.circleci/config.yml, Makefile
We never built ROCm images with MPI (more precisely, including Horovod without MPI). But when MPI/no MPI switch was introduced we kept building and publishing two identical ROCm images, without MPI, with endings "-0" and "-1" (normally `-0` means without MPI). A recent change stopped adding `-0` or `-1` ending to the ROCm image names. This change is to _actually stop building and publishing_ two identical images.
I also propose to restore adding the ending to the ROCm image just to be consistent with the naming of the other images and explicit about the fact that the image we are publishing has Horovod without MPI.
=> fix: do not build ROCm without MPI _twice_

.circleci/config.yml
This change addresses 2 separate issues.
1. The 2 deepspeed image types have MPI and no MPI flavors. The MPI flavor is useless. Stop building and publishing it.
2. The previous PR/commit attempted to skip MPI for ROCm. It worked for the dev build but not for the production build (see https://app.circleci.com/pipelines/github/determined-ai/environments ): in production we still built both MPI and no-MPI images. I suspect the reason for that is that the matrix specification for the production build does not explicitly list `dev-mode` as a parameter (the job `build-and-publish-docker` defines this parameter but it defaults to `false`) so the exclusion mechanism gets thrown off by the exclusion definition `{"dev-mode": false, "with-mpi": 1, "image-type": "pytorch10-tf27-rocm50"}` because it …
=> chore: do not build mpi flavor for deepspeed

Dockerfile-default-cpu, Dockerfile-default-gpu
If TORCH_PROFILER_GIT is specified, the installation _may_ roll protobuf back below 3.20 which results in it, in turn, being upgraded when determined wheel is installed. (I know, this is confusing: if protobuf is anything less than 3.20 when a container starts, the installation of determined will upgrade it to 4.21, and the incompatibility will result in crashing when Tensorflow is loaded).
My solution is to `pip install protobuf==3.20.1` at the very last moment before the conditional installation of horovod.
Given how the recent changes did not fix all the environments I wrote a little script to test this fix:
```
declare -a Images=(\
"determinedai/environments:cuda-11.1-pytorch-1.9-tf-2.4-gpu-0.19.4" \
"determinedai/environments:py-3.8-pytorch-1.9-tf-2.4-cpu-0.19.4" \ …
```
=> fix: pin protobuf just before installing horovod

Makefile
TORCH_VERSION was defined after the definition of image names for images containing tensorflow 2.7. As a result, images had an incorrect name, like `docker pull determinedai/environments:cuda-11.2-pytorch--tf-2.7-gpu-mpi-0.19.10`.
Move the definition above its first use in the Makefile.
Previous build: 
This branch:
=> fix: torch version in image name

Makefile
The substring `pytorch-1.12` was in the tags for images built without PyTorch. This mistake was introduced in cd272fd.
=> fix: remove pytorch from tf-2.7 image tags [MLG-311]

.circleci/config.yml
This PR upgrades our Docker images to use DeepSpeed 0.8.3 (up from 0.7.0). A major side-effect of this upgrade is that these images must be built on machine with a GPU present. This required waiting for our contract with CircleCI to renew as yearly, granting us access to their GPU instances. Using these required changes to our CircleCI configuration: we have split the build jobs into two sets, one with the same CPU setup as before and the other - for DeepSpeed and DeepSpeed/NeoX - with a GPU setup. 
These images have already been tested in the draft PR [#6614](https://github.com/determined-ai/determined/pull/6614). Specifically, the job `test-e2e-deepspeed` [succeeded](https://app.circleci.com/pipelines/github/determined-ai/determined/37272/workflows/0e0355d9-5528-44ec-aef8-441b21d2c648/jo …
=> chore: CircleCi GPU instances, DeepSpeed 0.8.3 [MLG-399]

cloud/environments-packer.json, dockerfile_scripts/install_libnss_determined.sh
[HELP-51](https://hpe-aiatscale.atlassian.net/browse/HELP-51)
In `nsswitch.conf` move "determined" to the front of the list so Determined-created identity entries are picked up first.  This prevents conflicting entries that may be added by the infrastructure.
In the ticket linked above, distributed training via SSH, e.g. Horovod, on OpenShift 4.+ gets thrown off by [CRI-O injecting a `passwd` entry](https://github.com/cri-o/cri-o/pull/2022/commits/77408ef1490002e62c88baacc5c994e97aa793c6) that interferes with the SSH client identity as expected by Determined.
@dougdet worked with @rb-determined-ai on this solution.
[HELP-51]: https://hpe-aiatscale.atlassian.net/browse/HELP-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: move "determined" to front in nsswitch.conf

Makefile
PyTorch 2.0 images are given an incorrect tag, such as `determinedai/environments:py-3.10-pytorch-1.12-cpu-42acaf5` . Replace `pytorch-1.12` with `pytorch-2.0`.
=> fix: tag torch 2 images as 2.0 and not 1.12

dockerfile_scripts/install_libnss_determined.sh
It appears that placing our libnss plugin first is good for openshift, but bad for slurm.
If we have to pick, we should optimize for the slurm users.
Additionally, placing our plugin last offers the least surprise, I think, as it doesn't override whatever else the user had configured in their image (which was the original motivation for having it last).
Our install_libnss_determined.sh now accepts a --first option to get the openshift-friendly behavior.  This is likely more useful as documentation strategy than for any real users.
=> fix: revert libnss_determined-goes-first

cloud/roles/nvidia-container-toolkit/tasks/main.yml
apparently nvidia decided to axe ubuntu22.04 images for nvidia-container-toolkit, and only support an older EOL 18.04...
see https://github.com/NVIDIA/nvidia-container-toolkit/issues/96 for appropriate context.
=> fix: nvidia only has ubuntu 18.04 images now [MLG-1194]

.circleci/config.yml, Dockerfile-ngc, Makefile, dockerfile_scripts/build_aws.sh
Update build-gpu-ngc-gh-deepspped for llama2 test.
Added WITH_NCCL support and revert AWS version to 1.4.0.
=> PAD-101: Updated build-gpu-ngc-gh-deepspeed to work with llama2 tests

cloud/roles/aws-fs/tasks/main.yml
MD-396
`efs-utils` was bumped from v1.36 to v2.0 which broke our install. This PR updates our install to match their [README](https://github.com/aws/efs-utils?tab=readme-ov-file#on-other-linux-distributions).
=> feat: fix install for efs-utils

Makefile, cloud/environments-packer.json
Set the images that are baked in to our AMIs and GCloud images to the shiny new NGC+ images.
=> feat: set NGC+ images as default
