Dockerfile.gpu

Includes fix for: https://github.com/determined-ai/horovod/pull/25

Bump horovod version.

---

Dockerfile.gpu

This new version fixes issues related to gradient updates of type
IndexedSlices when `sparse_to_dense` is false.

chore: bump horovod version

---

Dockerfile.gpu

This new version of HVD correctly increments optimizers iterations if 
applicable and support gradient aggregation for TF2.4+.

chore: bump hvd version

---

Dockerfile.gpu

chore: update horovod hash

---

Dockerfile.cpu
Dockerfile.gpu

The package provides `multilog`, a tool that we want to use in
Kubernetes to apply rotation to harness output log files.

chore: add daemontools package

---

.circleci/config.yml
Makefile

Push the docker images to the NGC registry.

ci: push docker images to the NGC registry

---

dockerfile_scripts/install_nccl_and_horovod.sh

Need to update environment images with a fix in our horovod branch (see DET-5243)

Update horovod sha

---

Makefile

This should shave off about 250 MiB.

Install a cpu wheel of TF2.4 in the cpu image

---

dockerfile_scripts/additional-requirements.txt

These are just heavily requested in product feedback. Should have minimal impact.

chore: add pands and matplotlib to images [DET-5447]

---

Dockerfile.cpu
Dockerfile.gpu
Makefile
dockerfile_scripts/torch-tb-profiler-patch.sh
dockerfile_scripts/torch_tb_profiler_patch.patch

including a patched version of torch-tb-profiler plugin in the CPU image which will be used by tensorboard startup

patch torch-tb-profiler plugin

---

Dockerfile-base-cpu
Dockerfile-base-gpu

feat: add nfs-common to the Docker images

---

cloud/roles/utilities/tasks/main.yml

bake nfs-common into agent image

---

Makefile
dockerfile_scripts/install_python.sh

- do not publish "legacy" TF 1.15 to NGC.
- remove pytorch 1.7 from TF 2.5 & 2.6 images.
- bump erroneous tf2-cpu 2.4.2 -> 2.4.3.
- get fresh conda.
- run conda upgrade / conda clean to update python packages shipped with conda, and then remove the outdated cached versions.
- reorder jobs in the makefile so cpu/gpu versions are next to each other, helping make sure they install the same dependency versions.

fix: vulnerabilities update.

---

Dockerfile-default-gpu
Makefile
dockerfile_scripts/additional-requirements.txt
dockerfile_scripts/install_python.sh

- Python 3.8.11 for newer images. NGC wants 3.7.12 which is not provided by conda. 3.9.x is not supported by TF2.4.
- Pull in an update in `pillow`.

fix: vulnerabilities 2021-09-22.

---

cloud/environments-packer.json

This also introduces auto-formatting to the environments-packer.json
file, so the amis can be updated automatically.

chore: update base amis

---

cloud/roles/utilities/tasks/main.yml
dockerfile_scripts/install_python.sh

- Run forced `conda clean` to absolutely, positively remove all outdated and vulnerable packages in conda caches. This should address the current anchore security scanning issue.
- Also do `apt-get upgrade` in the AMIs to make them more fresh. This is related to #128

fix: force-cleanup all conda caches, apt-get upgrade in AMIs.

---

dockerfile_scripts/install_deepspeed.sh

fix: add missing deepspeed dependency

---

Makefile

fix: gpt-neox unauthenticated git protocal issue

---

Dockerfile-default-cpu
Dockerfile-default-gpu
Makefile

https://determinedai.atlassian.net/browse/DET-6846
Don't install PTL inside environment images.
The intention is to modify our examples using PTL to install PTL in `startup-hook.sh`. Once I successfully build dev images, I will bump the version in https://github.com/determined-ai/determined/pull/4377 in the `determined` repository that does the PTL installation on an as-needed basis (in startup hooks) and will make sure it works with the environments built from this branch.

remove PyTorch Lightning DET-6846

---

.circleci/config.yml

fix: update circleci config for rocm 5.0 build

---

Dockerfile-default-cpu
Dockerfile-default-gpu
Dockerfile-default-rocm
Makefile

Apparently, that's what we have to do: either upgrade tensorflow (2.8 and 2.7 had new patches come out on Sep 2 that should have files generated with a recent protobuf), _or_ we PIN protbuf to 3.20 (for older versions of tensorflow).
https://determinedai.atlassian.net/browse/MLG-169

fix: upgrade tf OR pin protobuf

---

.circleci/config.yml
Makefile
cloud/ansible.cfg
cloud/environments-packer.json

https://determinedai.atlassian.net/browse/MLG-245

chore: Remove tensorflow 2.4 recipes

---

Makefile

chore: update pytorch and tensorflow versions in TF2 images

chore: update pytorch and tensorflow versions in TF2 images [MLG-14]

---

dockerfile_scripts/additional-requirements.txt

`protobuf==4.22.1` has leaked into the images.

chore: pin protobuf version more.

---

.circleci/config.yml
Dockerfile-default-cpu
Dockerfile-default-gpu
Makefile

chore: upgrade to tensorflow 2.11.0 [MLG-358]

---

.circleci/config.yml

fix: replace master with main in filters

---

Makefile

Upgrade our tf2 images to TensorFlow 2.11.1.

chore: tensorflow 2.11.1

---

cloud/roles/environments/tasks/main.yml

fix: Ansible/Docker workaround for "chunked" bug

---

cloud/environments-packer.json

Use g4dn.xlarge for gov zones.
This is addressing the following error:
```
Error launching source instance: InsufficientInstanceCapacity: We currently do not have sufficient p2.xlarge capacity in zones with support for 'gp2' volumes. Our system will be working on provisioning additional capacity.
```

fix: insufficient instance capacity error

---

.github/pull_request_template.md
README.md

Updating environments is a pain: it is complex and unintuitive. Document the process.

docs: explain dev workflow

---

dockerfile_scripts/notebook-requirements.txt

`ipywidgets` provides a better UI for `tqdm` progress bar. it was mentioned a few times over the years on slack, but somehow it has never been transformed into a PR.

feat: add `ipywidgets` package.

---

Makefile
dockerfile_scripts/build_aws.sh
dockerfile_scripts/build_nccl.sh
dockerfile_scripts/install_deepspeed.sh
dockerfile_scripts/ompi.sh

Updated AWS plugin version to 1.6.0, NGC version to 24.03, nccl to 2.20.5, OFI to 1.18.1 and OMPI to 4.1.5.

Updated AWS plugin to 1.6.0

---

Dockerfile-default-rocm
cloud/roles/nvidia-drivers/defaults/main.yml

MD-413
Fabric manager version and Nvidia driver version mismatch is causing issues.

fix: update nvidia driver version

---

.github/CODEOWNERS

chore: make CODEOWNERS

---

dockerfile_scripts/notebook-requirements.txt

chore: upgrade jupyter to 4 and notebook to 7
